import React from 'react';
import Home from '../client/components/Home';
import renderer from '../helpers/renderer';
import { ChunkExtractor } from '@loadable/server';
import path from 'path';

export const render = (req, res) => {
    // This is the stats file generated by webpack loadable plugin
    const statsFile = path.resolve(__dirname, '../../public/loadable-stats.json');

    // We create an extractor from the statsFile
    const extractor = new ChunkExtractor({ statsFile, entrypoints: ["home"] })

    // Wrap your application using "collectChunks"
    const jsx = extractor.collectChunks(<Home />)

    // You can now collect your script tags
    const scriptTags = extractor.getScriptTags() // or extractor.getScriptElements();

    // You can also collect your "preload/prefetch" links
    const linkTags = extractor.getLinkTags() // or extractor.getLinkElements();

    // And you can even collect your style tags (if you use "mini-css-extract-plugin")
    const styleTags = extractor.getStyleTags() // or extractor.getStyleElements();

    res.send(renderer(jsx, scriptTags, linkTags, styleTags));
}